### ISSUE TITLE
Extracting tile returns multi dim output from H&E qptiff

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#250]
I think this is specific to my scanner, when running the following line on my `qptiff` H&E svs file, 

`region = wsi.slide.extract_region(location = (900, 800), size = (500, 500))`

I get a 5 dimensional object, which is incompatible for downstream analysis. 

Do you think it may be useful to run a np.squeeze right before returning the array in `wsi.slide.extract_region`?

**Comment by ryanccarelli** [comment]
Bioformats converts everything to OME-TIFF with dimensions (x, y, z, channel, time). Since you are loading .qptiff with the bioformats backend this is the expected behavior (and many .qptiff files will use the channel or time dimension so we should keep this default). If you are running a pipeline then the quick fix is to add a transform that collapses the channels at the beginning of your pipeline. Something like:

```python3
import numpy as np
from pathml.core import Tile
from pathml.preprocessing.transforms import Transform
class Squeeze(Transform):
    def __repr__(self):
        return f"Squeeze"

    def F(self, image):
        return np.squeeze(image)

    def apply(self, tile):
        assert isinstance(
            tile, Tile
        ), f"tile is type {type(tile)} but must be pathml.core.tile.Tile"
        tile.image = self.F(tile.image)
```

@jacobrosenthaldfci what do you think of adding a flag to extract_region that lets the user squeeze out dimensions that aren't being used.

**Comment by jacobrosenthaldfci** [comment]
Hmmm. I don't think adding a squeeze step inside `BioformatsBackend.extract_region()` is a good idea, because then the dimensions of the output would vary based on the region being extracted. I also don't think adding a squeeze flag to the function call is ideal, because it seems like a pretty trivial step that any user can do themselves and would come at the expense of cluttering the API.

Here's one idea which I think could help streamline the API and make things more consistent:
- Add a `SlideData.extract_region()` method which calls through to the `extract_region()` method of whichever backend is being used.
- Check `self.slide_type.rgb` and return either a 3-dimensional XYC array (if it's an rgb image) or a 5-dimensional XYZCT array otherwise.

Users could use `SlideData.extract_region()` instead of `SlideData.slide.extract_region()` which might be more intuitive. And then the behavior (number of dims in returned array) would depend on the `slide_type` which the user is already specifying, so it would be predictable and we wouldn't have to add any extra flags.

Thoughts? @ryanccarelli @surya-narayanan

**Comment by ryanccarelli** [comment]
I like the idea that this could be inferred through slide_type but for sure some users will have xyzc images in rgb

**Comment by jacobrosenthaldfci** [comment]
Ah yeah true. Would it be feasible to create a set of rules to map between slide_type and number of dims?

**Comment by jacobrosenthaldfci** [comment]
Otherwise I think we should leave as is. @surya-narayanan can you just add an np.squeeze as needed in your workflow? Maybe I can add a note in the documentation to say that dimensions of returned array will vary depending on which backend is being used

**Comment by surya-narayanan** [comment]
I can work with that. Thanks all, have a good day.
