### ISSUE TITLE
Add tutorials/functions about whole slide image inference 

### ISSUE THREAD

**Issue by JunMa11** [Dana-Farber-AIOS/pathml#263]
Dear pathml team,

Thanks for sharing this great tool.

It seems that pathml does not have functions for predicting the whole slide images.
For example, after training a nuclei segmentation and classification model (e.g., Hovernet), I'd like to use this model to predict a whole slide image (WSI) with just one line of code.

Would it be possible for you to consider adding this function and creating a tutorial? These demo [WSIs](https://openslide.org/demo/) can be used as testing images.

Here is an example: https://github.com/markowetzlab/pathml

**Comment by jacobrosenthaldfci** [comment]
Hi, thanks for the feedback!
Right now, if you want to run inference for each tile, you could do it three ways:

1. loop through each tile using [`SlideData.generate_tiles()`](https://pathml.readthedocs.io/en/latest/api_core_reference.html#pathml.core.SlideData.generate_tiles)

````python
wsi = HESlide("/path/to/slide.svs")
for tile in wsi.generate_tiles():
    tile_prediction = model(tile.image)
````
2. create a [`TileDataset`](https://pathml.readthedocs.io/en/latest/api_ml_reference.html#h5path-dataset) and use that to run inference with a model

````python
dataset = TileDataset("/path/to/processed_slide.h5path")
dataloader = DataLoader(dataset, batch_size = 16, num_workers = 4)

for tile_image_batch, tile_masks_batch, tile_labels_batch, slide_labels_batch in dataloader:
    batch_prediction = model(tile_image_batch)
````

3. create a `Transform` that applies the model, and use it in a `Pipeline` with `SlideData.run()`. This is more complicated, but you could use the [`SegmentMIF`](https://github.com/Dana-Farber-AIOS/pathml/blob/2721cb736599359734ca5ad8bbf7dd66acfc1832/pathml/preprocessing/transforms.py#L1249) transform as an example along with the section of the documentation about [how to make custom transforms](https://pathml.readthedocs.io/en/latest/creating_pipelines.html#creating-custom-transforms). The benefit of this is that it could be combined in a pipeline along with other transformations.



The above is just pseudocode but I hope it helps point you in the right direction. Then once you have tile-level predictions, it will depend on your specific use-case what you want to do next. It's hard to make a one-liner because there are so many different possible downstream applications that people might want to do. But hopefully this is helpful and will be able to fit with your workflow
