### ISSUE TITLE
Storing tiles as by marker instead of a single tile

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#285]
**Is your feature request related to a problem? Please describe.**
In multi-channel images, especially with a big tile size (1024+), loading a whole image in a dataloader often causes cpu bottlenecks if I want to manipulate the image somehow in memory before feeding it to my gpus. This forces me to keep my batch size relatively small. 

To combat this, I don't mind doing analysis on just one channel from my 7 channel image. Is it possible to save the tile as a dictionary of `{marker : tile_slice} `where each rather than a single array of size `markers x tile_size x tile_size`?

I'm happy to have a discussion around this.

**Comment by jacob-rosenthal** [comment]
One option is to make your own custom dataloader. For example, you could just copy all the code for `TileDataset` and at the end, instead of returning `im`, just return `im[:, :, :, channel_ix, :]` or something similar. 

https://github.com/Dana-Farber-AIOS/pathml/blob/1010b3a870cff49747d9277740ba5af5d4bf9fcc/pathml/ml/dataset.py#L84

**Comment by surya-narayanan** [comment]
Do you think that would be worth making a general feature? Leaving it as an option to consider.
