### ISSUE TITLE
preprocessing for ome.tif for segmentation

### ISSUE THREAD

**Issue by jamesMo84** [Dana-Farber-AIOS/pathml#313]
XYCZT ome.tif images are imported by (https://pathml.readthedocs.io/en/latest/examples/link_loading_images.html#Volumetric-+-time-series-OME-TIFF)
preprocessing API CollapseRunsCODEX(z) returns error as slides were not imported by CODEXSlide
is there a preprocessing step for ome.tif to prepare correct pyramid plane for segmentation?
thanks!

**Comment by jacob-rosenthal** [comment]
Hi @jamesMo84 , Since `CollapseRunsCODEX` is meant only for images generated by the CODEX platform, there's a check to ensure that `platform == "CODEX"`:
https://github.com/Dana-Farber-AIOS/pathml/blob/adb6a0acf3d03681ef1c083dbe68b89d5c1982a7/pathml/preprocessing/transforms.py#L1575-L1577

To make sure that the platform is correctly specified, you can pass `platform="CODEX"` or `slide_type= pathml.core.types.CODEX` when loading the SlideData object, or you can use the [`CODEXSlide` convenience class](https://pathml.readthedocs.io/en/latest/api_core_reference.html#pathml.core.CODEXSlide)

More about specifying slide types is documented here: https://pathml.readthedocs.io/en/latest/api_core_reference.html#slide-types

Hope this is helpful! Thanks
