### ISSUE TITLE
Running a preprocessing pipeline on a Vectra slide with 3 levels

### ISSUE THREAD

**Issue by MohamedOmar2020** [Dana-Farber-AIOS/pathml#321]
I have some vectra slides with multiple levels. I need to run the pipeline on the highest resolution (level 0)

When using 
slide_bi016966.run(pipe, distributed = False, tile_size=(5933, 2134), tile_pad=False, overwrite_existing_tiles=True), I get this error:

> raceback (most recent call last):
>   File "/Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-9-5200f547eec6>", line 1, in <cell line: 1>
>     slide_bi016966.run(pipe, distributed = False, tile_size=(5933, 2134), tile_pad=False, overwrite_existing_tiles=True)
>   File "/Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/pathml/core/slide_data.py", line 337, in run
>     for tile in self.generate_tiles(
>   File "/Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/pathml/core/slide_data.py", line 404, in generate_tiles
>     for tile in self.slide.generate_tiles(shape, stride, pad, **kwargs):
>   File "/Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/pathml/core/slide_backends.py", line 596, in generate_tiles
>     tile_im = self.extract_region(
>   File "/Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/pathml/core/slide_backends.py", line 477, in extract_region
>     array[:, :, z, :, t] = slicearray
> ValueError: could not broadcast input array from shape (5933,2134,3) into shape (5933,2134,7)
> 

The same when adding level=0 in slide.run()

**Comment by jacob-rosenthal** [comment]
Hi @MohamedOmar2020 , can you put the code you are using to load `slide_bi016966`? What backend is it using? Is this a MISI image?

**Comment by MohamedOmar2020** [comment]
Hi @jacob-rosenthal. Yes it is a Vectra image from the MISI lab. This is the code for loading the image
```
slide_bi016966 = VectraSlide(
    f"/Volumes/Mohamed/MISI/Magnani Mice/stitched_new/MISI3542i_W21-04143_bi016966_M394_OVX_LM.tif", backend="bioformats", dtype=np.dtype("int8")
)
```

**Comment by jacob-rosenthal** [comment]
Hi @MohamedOmar2020 , 

Thanks for sending the image. I'm not sure exactly why this is happening, but I think it may be connected to a problem with the metadata and bioformats. Python-bioformats isn't being maintained/developed anymore, so replacing it is on the roadmap, but we haven't had bandwidth to work on this. In the meantime, I think I found a workaround

Looking at the output of `showinf` on the file, I saw that it included the following line: 
```
RGB = true (7) 
```
I thought this was weird because it seems to be saying that the image is RGB, even though it also says (correctly) that it has 7 channels. Maybe this is why it is only extracting arrays with 3 channels (causing the error message you pasted above).

So, we can use `bfconvert` and pass the `-separate` flag to make a new image with the channels split apart. In my testing, I also found that I needed to specify the correct series as well (e.g. 0, 1, or 2). The resulting single-level, multi-channel image seemed to work with the Bioformatsbackend in PathML

So the command would look something like the following:
```
bfconvert -series 1 -separate image.tif image_series1_separated.tif
```
And then you would use `image_series1_separated.tif` for further analysis

Both `bfconvert` and `showinf` can be downloaded from Conda as part of the `bftools` package from OME: `conda install -c ome bftools`

Can you give this a try and let me know if it resolved the problem?

**Comment by MohamedOmar2020** [comment]
Hi @jacob-rosenthal I think your solution is working great! Thanks!!
