### ISSUE TITLE
question

### ISSUE THREAD

**Issue by afshinmoradi** [Dana-Farber-AIOS/pathml#322]
Dear,

There is one question and one issue.
I am going to use your pipeline for around 200 -300 CODEX slides.

1_Can you please give me clue about performance of the required system like CPU or GPU and memory approximately?

2- In step 6 of the below link, I got the error "array is not supported". I can not make an image. adata is created.

https://pathml.readthedocs.io/en/latest/examples/link_multiplex_if.html

Your help is appreciated.

Best regards,

afshin

**Comment by jacob-rosenthal** [comment]
Hi Afshin, in order to help troubleshoot, could you please include a code snippet to reproduce the error? We need more information to be able to debug what you are seeing.
https://stackoverflow.com/help/minimal-reproducible-example

In terms of system requirements, there aren't any hard requirements. I've run CODEX pipelines on my laptop before (it's slow, but doable). More compute should make the pipelines run faster though.
