### ISSUE TITLE
Error at model training step  

### ISSUE THREAD

**Issue by archanabhardwaj** [Dana-Farber-AIOS/pathml#323]
Hello 

I am trying to run my data with Pathml . I followed all the steps as given in the tutorial for preprocessing of the data. https://github.com/Dana-Farber-AIOS/pathml/blob/master/examples/vignettes/workflow_HE_vignette.ipynb 

Next in order to train the model , I am following script as given in https://pathml.readthedocs.io/en/latest/examples/link_train_hovernet.html . For this loaded my data as given below : 

from pathml.ml import TileDataset
from torch.utils.data import DataLoader

dataset = TileDataset("ID1-preprocessed.h5path")
dataloader = DataLoader(dataset, batch_size = 16, num_workers = 1)

But it gives me error in main training loop section : 

AttributeError                            Traceback (most recent call last)
<ipython-input-43-ab9a95c82b75> in <module>
     27         images = data[0].float().to(device)
     28         masks = data[1].to(device)
---> 29         hv = data[2].float().to(device)
     30         tissue_type = data[3]
     31 

AttributeError: 'dict' object has no attribute 'float'
 
I would really appreciate your help. 

Thanks in advance

**Comment by jacob-rosenthal** [comment]
Hi, the details of the items yielded different dataloaders can vary. For example, the dataloader for PanNukeDataModule is different from the generic TileDataset. 

`PanNukeDataModule.train_dataloader` yields tuples of `(image, mask, tissue_type)`, or `(image, mask, hv, tissue_type)` for HoVer-Net, where:
- `image` is an array
- `mask` is an array
- `hv` is an array
- `tissue_type` is a strinng

`TileDataset` however yields tuples of `(tile_image, tile_masks, tile_labels, slide_labels)` where:
- `tile_image` is an array
- `tile_masks` is an array
- `tile_labels` is a dict
- `slide_labels` is a dict

This is documented [here (PanNuke)](https://pathml.readthedocs.io/en/latest/api_datasets_reference.html#pannuke) and [here (TileDataset)](https://pathml.readthedocs.io/en/latest/api_ml_reference.html#pathml.ml.TileDataset)

I think the error you are seeing is because the code is expecting the structure of a PanNuke dataloader (where the 3rd item is an array) but it is instead getting the dataloader from a standard TileDataset (where the 3rd item is a dict). For this reason, it's important to be very careful when setting up the dataloader, and a dataloader for one dataset might not work for a different dataset. I suggest writing the dataloader and training loops for your model yourself, to make sure that they are correct for your application, using the example notebooks as a guide instead of copy pasting
