### ISSUE TITLE
print c_count.value Missing parentheses in call to 'print'. 

### ISSUE THREAD

**Issue by luzy05111036** [Dana-Farber-AIOS/pathml#340]
**Describe the bug**
when I import this package
from pathml.datasets.pannuke import PanNukeDataModule
from pathml.ml.hovernet import HoVerNet, loss_hovernet, post_process_batch_hovernet
from pathml.ml.utils import wrap_transform_multichannel, dice_score

It shows this error   SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?

**To Reproduce**

run the following 
from pathml.datasets.pannuke import PanNukeDataModule
from pathml.ml.hovernet import HoVerNet, loss_hovernet, post_process_batch_hovernet
from pathml.ml.utils import wrap_transform_multichannel, dice_score
**Expected behavior**
There should be no error
**Screenshots**
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/70253071/205470177-ee77abf8-09db-4319-9e97-3830209a62b1.png">

**Additional context**

**Comment by jacob-rosenthal** [comment]
Hi, looks like the error is coming from pynvml package. It's probably a problem with environment setup. Looks like the path to the pynvml package is from outside the conda environment, so could be that the package is an older version previously installed with python 2. Maybe try creating a fresh environment from scratch, or installing a newer version of pynvml. Otherwise you can try opening an issue with the pynvml maintainers

**Comment by luzy05111036** [comment]
I installed the update pynvml and reinstall the environment, but still can't solve this problem. Because this is running the HPC. I do not have the authority to modify pynvml. Any further thought about this problem.

**Comment by luzy05111036** [comment]
I use new cude version and this problem is solved.  cuda11.4/toolkit/11.4.2
